### ISSUE TITLE
Convert to Lua?

### ISSUE THREAD

**Issue by bignimbus** [michaelb/do-nothing.vim#2]
Since NeoVim 0.5 was released, all I've been hearing about is Lua plugins. I strongly feel this important project should get on the hype train and dump Vimscript for Lua.

**Comment by michaelb** [comment]
I'm all for, but at the same time I still want to cater to Vim users as much as possible.

Is the introduction of lua really necessary? I didn't met any performance issue but it's true not everyone has a fast computer. Because lua for the sake of lua doesn't quite make sense to me.... I can make an exception for neovim, but it would be rather ironical that this plugin gets 'bloated'


If the introduction of lua:


1 - doesn't break vim compatibility

2 - maintain feature parity

3 - improve the neovim experience (even if it's just placebo, if the users are happier with lua I'll give them lua)



Then consider the related PR merged.

(A simple check for 1 and 2 would be enough)

**Comment by michaelb** [comment]
Thanks to the contribution of @vinodnimbalkar  I can probably say your request was implemented. Feel free to reopen if something is not up to par
